Repository quattor/configuration-modules-core, pull requests merged in 2021-04, with the labels that each got.

#1486 ncm-metaconfig: dynaFile (rsyslog) is a name of a template, not a path
  ncm-metaconfig/src/main/metaconfig/rsyslog/pan/actions.pan
Labels: bug

#1391 ncm-opennebula: include OpenNebula 5.8.x and vmgroups support
  ncm-opennebula/src/main/pan/components/opennebula/schema.pan
  ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
  ncm-opennebula/src/main/perl/OpenNebula/Server.pm
  ncm-opennebula/src/main/perl/opennebula.pm
  ncm-opennebula/src/main/resources/oned_level1.tt
  ncm-opennebula/src/main/resources/tests/profiles/vm.pan
  ncm-opennebula/src/main/resources/tests/profiles/vmgroup.pan
  ncm-opennebula/src/main/resources/tests/regexps/aii_vmtemplate/simple
  ncm-opennebula/src/main/resources/tests/regexps/oned/oned_template
  ncm-opennebula/src/main/resources/tests/regexps/vmgroup/simple
  ncm-opennebula/src/main/resources/vmgroup.tt
  ncm-opennebula/src/main/resources/vmtemplate.tt
  ncm-opennebula/src/test/perl/rpcdata.pm
  ncm-opennebula/src/test/perl/vmgroup.t
  ncm-opennebula/src/test/resources/one.pan
  ncm-opennebula/src/test/resources/vmgroup.pan
Labels: enhancement

#1456 ncm-opennebula: include 5.12.x support
  ncm-opennebula/src/main/pan/components/opennebula/common.pan
  ncm-opennebula/src/main/pan/components/opennebula/monitord.pan
  ncm-opennebula/src/main/pan/components/opennebula/schema.pan
  ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
  ncm-opennebula/src/main/perl/OpenNebula/Server.pm
  ncm-opennebula/src/main/perl/opennebula.pm
  ncm-opennebula/src/main/resources/monitord.tt
  ncm-opennebula/src/main/resources/oned.tt
  ncm-opennebula/src/main/resources/oned_level1.tt
  ncm-opennebula/src/main/resources/tests/profiles/monitord.pan
  ncm-opennebula/src/main/resources/tests/regexps/monitord/simple
  ncm-opennebula/src/main/resources/tests/regexps/oned/oned_template
  ncm-opennebula/src/main/resources/tests/regexps/oned/simple
  ncm-opennebula/src/test/perl/opennebula.t
  ncm-opennebula/src/test/resources/monitord.pan
  ncm-opennebula/src/test/resources/one.pan
Labels: backwards incompatible
