Repository quattor/configuration-modules-core, pull requests merged in 2023-07, with the labels that each got.

#1599 ncm-ntpd: fix type of ntpd_tinker_options/step #1600
  ncm-ntpd/src/main/pan/components/ntpd/schema.pan
Labels: bug

#1546 ncm-ipmi: Enhancements to IPMI module
  ncm-ipmi/src/main/pan/components/ipmi/schema.pan
  ncm-ipmi/src/main/perl/ipmi.pm
  ncm-ipmi/src/test/perl/configure.t
  ncm-ipmi/src/test/perl/pod-syntax.t
  ncm-ipmi/src/test/resources/ipmi.pan
Labels: backwards incompatible

#1258 ncm-spma: apt: Finish implementation
  ncm-spma/src/main/perl/spma/apt.pm
  ncm-spma/src/main/resources/apt/source.tt
  ncm-spma/src/main/resources/tests/profiles/apt-sources.pan
  ncm-spma/src/main/resources/tests/regexps/apt-sources/standard
  ncm-spma/src/main/resources/tests/regexps/apt-sources/trusted
  ncm-spma/src/test/perl/apt-sources-generate.t
Labels: bug, enhancement
