Repository quattor/configuration-modules-core, pull requests merged in 2024-12, with the labels that each got.

#1768 ncm-puppet: Cleanup pan templates
  ncm-puppet/src/main/pan/components/puppet/config-rpm.pan
  ncm-puppet/src/main/pan/components/puppet/schema.pan
Labels: cleanup

#1763 ncm-authconfig: Use choice type where possible
  ncm-authconfig/src/main/pan/components/authconfig/schema.pan
  ncm-authconfig/src/main/pan/components/authconfig/sssd/ipa.pan
  ncm-authconfig/src/main/pan/components/authconfig/sssd/ldap.pan
  ncm-authconfig/src/main/pan/components/authconfig/sssd/tls.pan
Labels: bug, cleanup

#1766 ncm-sudo: Cleanup pan templates
  ncm-sudo/src/main/pan/components/sudo/validation.pan
  ncm-sudo/src/test/resources/1line.pan
  ncm-sudo/src/test/resources/all_aliases.pan
  ncm-sudo/src/test/resources/new_opts.pan
  ncm-sudo/src/test/resources/test0aliases.pan
  ncm-sudo/src/test/resources/test1aliases.pan
  ncm-sudo/src/test/resources/test1aliases_cmd.pan
  ncm-sudo/src/test/resources/test1aliases_cmderr.pan
  ncm-sudo/src/test/resources/test1aliases_runas.pan
  ncm-sudo/src/test/resources/test1aliases_runaserr.pan
  ncm-sudo/src/test/resources/test1aliaseserr.pan
  ncm-sudo/src/test/resources/test1option.pan
  ncm-sudo/src/test/resources/test2options.pan
  ncm-sudo/src/test/resources/test_2_general_options_errru.pan
  ncm-sudo/src/test/resources/test_2_general_options_valid_types.pan
  ncm-sudo/src/test/resources/test_2_general_options_validuh.pan
  ncm-sudo/src/test/resources/test_general_options_errru.pan
  ncm-sudo/src/test/resources/test_general_options_valid.pan
  ncm-sudo/src/test/resources/test_general_options_validh.pan
  ncm-sudo/src/test/resources/test_general_options_validr.pan
  ncm-sudo/src/test/resources/test_general_options_validu.pan
  ncm-sudo/src/test/resources/testoptionerr.pan
Labels: cleanup

#1765 ncm-syslog: Fix wrapping and indentation in pan
  ncm-syslog/src/test/resources/basic.pan
Labels: cleanup

#1769 ncm-shorewall: Fix wrapping and indentation in pan
  ncm-shorewall/src/main/pan/components/shorewall/schema.pan
Labels: cleanup

#1772 ncm-pam: Fix wrapping and indentation in pan
  ncm-pam/src/main/pan/components/pam/config.pan
  ncm-pam/src/main/pan/components/pam/schema.pan
  ncm-pam/src/test/resources/simple.pan
Labels: cleanup

#1767 ncm-ssh: Cleanup pan templates
  ncm-ssh/src/main/pan/components/ssh/schema-5.3.pan
  ncm-ssh/src/main/pan/components/ssh/schema.pan
  ncm-ssh/src/test/resources/ssh_simple.pan
Labels: cleanup

#1774 ncm-postgresql: Cleanup pan templates
  ncm-postgresql/src/main/pan/components/postgresql/schema.pan
Labels: cleanup

#1781 ncm-syslogng: Fix wrapping and indentation in pan
  ncm-syslogng/src/main/pan/components/syslogng/schema.pan
Labels: cleanup

#1780 ncm-profile: Cleanup pan templates
  ncm-profile/src/main/pan/components/profile/functions.pan
  ncm-profile/src/main/pan/components/profile/schema.pan
Labels: cleanup

#1779 ncm-metaconfig: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/pan/components/metaconfig/schema.pan
  ncm-metaconfig/src/test/resources/commands_fail_pre.pan
Labels: cleanup

#1770 ncm-postfix: Fix wrapping and indentation in pan
  ncm-postfix/src/main/pan/components/postfix/config.pan
  ncm-postfix/src/main/pan/components/postfix/schema.pan
Labels: cleanup

#1773 ncm-openstack: Fix wrapping and indentation in pan
  ncm-openstack/src/main/pan/components/openstack/catalog.pan
  ncm-openstack/src/main/pan/components/openstack/common.pan
  ncm-openstack/src/main/pan/components/openstack/compute/nova.pan
  ncm-openstack/src/main/pan/components/openstack/container-infra.pan
  ncm-openstack/src/main/pan/components/openstack/dashboard/horizon.pan
  ncm-openstack/src/main/pan/components/openstack/identity/gather.pan
  ncm-openstack/src/main/pan/components/openstack/image/glance.pan
  ncm-openstack/src/main/pan/components/openstack/key-manager.pan
  ncm-openstack/src/main/pan/components/openstack/orchestration.pan
  ncm-openstack/src/main/pan/components/openstack/share/manila.pan
  ncm-openstack/src/main/resources/tests/profiles/horizon.pan
Labels: cleanup

#1762 ncm-opennebula: Cleanup pan templates
  ncm-opennebula/src/main/pan/components/opennebula/common.pan
  ncm-opennebula/src/main/pan/components/opennebula/schema.pan
  ncm-opennebula/src/main/pan/components/opennebula/sudo.pan
  ncm-opennebula/src/main/pan/quattor/aii/opennebula/functions.pan
  ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
  ncm-opennebula/src/main/resources/tests/profiles/vm.pan
  ncm-opennebula/src/test/resources/one.pan
  ncm-opennebula/src/test/resources/vm.pan
Labels: cleanup

#1758 ncm-icinga: Cleanup pan templates
  ncm-icinga/src/main/pan/components/icinga/functions.pan
  ncm-icinga/src/main/pan/components/icinga/schema.pan
Labels: cleanup

#1751 ncm-cron: Cleanup pan templates
  ncm-cron/src/main/pan/components/cron/config.pan
  ncm-cron/src/main/pan/components/cron/schema.pan
Labels: cleanup

#1803 ncm-metaconfig: slurm: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/slurm/pan/schema_20.11.pan
  ncm-metaconfig/src/main/metaconfig/slurm/pan/schema_21.08.pan
  ncm-metaconfig/src/main/metaconfig/slurm/pan/schema_23.02.pan
  ncm-metaconfig/src/main/metaconfig/slurm/pan/schema_24.05.pan
  ncm-metaconfig/src/main/metaconfig/slurm/tests/profiles/config.pan
  ncm-metaconfig/src/main/metaconfig/slurm/tests/profiles/spank.pan
Labels: cleanup

#1802 ncm-metaconfig: ssh: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/ssh/pan/schema.pan
  ncm-metaconfig/src/main/metaconfig/ssh/pan/server_config.pan
  ncm-metaconfig/src/main/metaconfig/ssh/tests/profiles/client_config.pan
  ncm-metaconfig/src/main/metaconfig/ssh/tests/profiles/server_config.pan
Labels: cleanup

#1801 ncm-metaconfig: xinetd: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/xinetd/pan/schema.pan
Labels: cleanup

#1798 ncm-metaconfig: kafka: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/kafka/tests/profiles/config.pan
Labels: cleanup

#1796 ncm-metaconfig: dellnetworking: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/dellnetworking/pan/schema.pan
Labels: cleanup

#1795 ncm-metaconfig: cumulus: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/cumulus/tests/profiles/acl.pan
  ncm-metaconfig/src/main/metaconfig/cumulus/tests/profiles/frr.pan
Labels: cleanup

#1794 ncm-metaconfig: conntrackd: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/conntrackd/pan/schema.pan
Labels: cleanup

#1793 ncm-metaconfig: chrony: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/chrony/pan/schema.pan
Labels: cleanup

#1792 ncm-metaconfig: carbon-relay-ng: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/carbon-relay-ng/tests/profiles/config.pan
Labels: cleanup

#1807 ncm-spma: fix to retain rpms listed in whitelist path
  ncm-spma/src/main/perl/spma/dnf.pm
Labels: bug

#1789 ncm-systemd: Cleanup pan templates
  ncm-systemd/src/main/pan/components/systemd/functions.pan
  ncm-systemd/src/main/pan/components/systemd/schema.pan
  ncm-systemd/src/main/resources/custom/tests/profiles/unitfile.pan
  ncm-systemd/src/main/resources/regular/tests/profiles/unitfile.pan
  ncm-systemd/src/test/resources/service-chkconfig_simple_services.pan
  ncm-systemd/src/test/resources/service_services_ceph021.pan
  ncm-systemd/src/test/resources/unitfile_config.pan
Labels: cleanup

#1785 ncm-metaconfig: named: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/named/pan/schema.pan
  ncm-metaconfig/src/main/metaconfig/named/tests/profiles/config.pan
Labels: cleanup

#1790 ncm-spma: Cleanup pan templates
  ncm-spma/src/main/pan/components/spma/functions.pan
  ncm-spma/src/test/resources/ips-run.pan
Labels: cleanup

#1791 ncm-metaconfig: devicemapper: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/devicemapper/pan/schema.pan
Labels: cleanup

#1800 ncm-metaconfig: zookeeper: Fix wrapping and indentation in pan
  ncm-metaconfig/src/main/metaconfig/zookeeper/pan/schema.pan
Labels: cleanup
