Repository quattor/configuration-modules-core, pull requests merged in 2024-11, with the labels that each got.

#1719 network: nmstate add support for ovsintport and ovsbridge
  ncm-network/src/main/perl/network.pm
  ncm-network/src/main/perl/nmstate.pm
  ncm-network/src/test/perl/nmstate_advance.t
  ncm-network/src/test/resources/nmstate_advance.pan
Labels: enhancement

#1720 ncm-network: Move nmstate options to new schema
  ncm-network/src/main/pan/components/network/core-schema-legacy.pan
  ncm-network/src/main/pan/components/network/core-schema.pan
  ncm-network/src/main/pan/components/network/types/network.pan
  ncm-network/src/main/pan/components/network/types/network/backend/initscripts.pan
  ncm-network/src/main/pan/components/network/types/network/backend/nmstate.pan
  ncm-network/src/main/pan/components/network/types/network/route.pan
  ncm-network/src/main/perl/nmstate.pm
  ncm-network/src/test/perl/nmstate_simple.t
  ncm-network/src/test/resources/nmstate_simple.pan
Labels: backwards incompatible

#1727 ncm-metaconfig: upstream minor schema changes
  ncm-metaconfig/src/main/metaconfig/kafka/pan/config.pan
  ncm-metaconfig/src/main/metaconfig/kafka/tests/profiles/config.pan
  ncm-metaconfig/src/main/metaconfig/kafka/tests/regexps/config/base
  ncm-metaconfig/src/main/metaconfig/mailrc/pan/schema.pan
  ncm-metaconfig/src/main/metaconfig/slurm/pan/schema_23.02.pan
  ncm-metaconfig/src/main/metaconfig/slurm/pan/schema_24.05.pan
  ncm-metaconfig/src/main/metaconfig/zkrsync/pan/schema.pan
Labels: enhancement

#1659 ncm-network: nmstate - add additional route rule parameters
  ncm-network/src/main/pan/components/network/types/network/backend/initscripts.pan
  ncm-network/src/main/pan/components/network/types/network/backend/nmstate.pan
  ncm-network/src/main/pan/components/network/types/network/rule.pan
  ncm-network/src/main/perl/nmstate.pm
  ncm-network/src/test/perl/nmstate_route_rule.t
  ncm-network/src/test/resources/nmstate_advance.pan
  ncm-network/src/test/resources/nmstate_route_rule.pan
Labels: enhancement

#1741 ncm-network: nmstate: Fix indentation errors
  ncm-network/src/main/pan/components/network/types/network/backend/nmstate.pan
  ncm-network/src/test/resources/nmstate_advance.pan
Labels: cleanup

#1742 ncm-sudo: Add support for use_pty with sudoers
  ncm-sudo/src/main/pan/components/sudo/schema.pan
Labels: enhancement

#1744 Documentation fixes
  ncm-metaconfig/src/main/metaconfig/conntrackd/pan/schema.pan
  ncm-network/src/main/perl/nmstate.pm
  ncm-sudo/src/main/pan/components/sudo/schema.pan
Labels: cleanup

#1737 ncm-opennebula: add cpu overcommit ratio option
  ncm-opennebula/src/main/pan/quattor/aii/opennebula/schema.pan
  ncm-opennebula/src/main/resources/tests/profiles/vm.pan
  ncm-opennebula/src/main/resources/vmtemplate.tt
  ncm-opennebula/src/test/resources/vm.pan
Labels: enhancement

#1747 ncm-accounts: Fix wrapping and indentation in pan
  ncm-accounts/src/main/pan/components/accounts/functions.pan
Labels: cleanup

#1748 ncm-authconfig: Fix wrapping and indentation in pan
  ncm-authconfig/src/main/pan/components/authconfig/sssd/ldap.pan
  ncm-authconfig/src/main/pan/components/authconfig/sssd/tls.pan
Labels: cleanup

#1749 ncm-ccm: Fix wrapping and indentation in pan
  ncm-ccm/src/main/pan/components/ccm/schema.pan
  ncm-ccm/src/test/resources/base.pan
Labels: cleanup

#1753 ncm-filesystems: Fix wrapping and indentation in pan
  ncm-filesystems/src/test/resources/devices.pan
Labels: cleanup

#1754 ncm-freeipa: Cleanup pan templates
  ncm-freeipa/src/main/pan/quattor/aii/freeipa/schema.pan
  ncm-freeipa/src/test/resources/server.pan
Labels: cleanup

#1755 nc-fstab: Cleanup pan templates
  ncm-fstab/src/test/resources/configure.pan
Labels: cleanup

#1756 ncm-gmetad: Fix wrapping and indentation in pan
  ncm-gmetad/src/main/pan/components/gmetad/schema.pan
Labels: cleanup

#1757 ncm-grub: Fix wrapping and indentation in pan
  ncm-grub/src/main/pan/components/grub/schema.pan
Labels: cleanup

#1759 ncm-mysql: Fix wrapping and indentation in pan
  ncm-mysql/src/main/pan/components/mysql/schema.pan
Labels: cleanup

#1760 ncm-nagios: Cleanup pan templates
  ncm-nagios/src/main/pan/components/nagios/schema.pan
Labels: cleanup

#1761 ncm-openldap: Cleanup pan templates
  ncm-openldap/src/main/pan/components/openldap/config.pan
  ncm-openldap/src/main/pan/components/openldap/schema.pan
Labels: cleanup
